# define language and JDK version, we use JAVA 8 and tha code should pass both with Oracle JDK and OpenJDK
language: java
jdk:
  - openjdk8
# Define OS image for TravisCI to use: Ubuntu 14.04 LTS (Trusty Tahr)
dist: trusty
# install necessary tools for code coverage reporters
after_success:
  # the actual testing
  - mvn clean test
  # create single-jar build
  - mvn clean compile assembly:single
before_deploy:
  - export DEPLOYED_FILE=$(target/release-test-jar-with-dependencies.jar)
  - echo "deploying ${DEPLOYED_FILE} to GitHub releases"
  - sudo chown travis ${DEPLOYED_FILE}
#  - "cp target/release-test-jar-with-dependencies.jar target/release-test.jar"
#  # Set up git user name and tag this commit
#  - git config --local user.name "pintergreg"
#  - git config --local user.email "pinter.gergo@vipmail.hu"
#  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  # If no tag is set, deploy as nightly
  - if [ !${TRAVIS_TAG} ] ; then export TRAVIS_TAG=Nightly ; fi
deploy:
  provider: releases
  api_key:
    secure: nz76hynet3vgLaWFBshx4P788BNs9n5F5kgjbhpRlbPJMtrm2BYV503V+sQQkVKbzPhwtdNjTicK+Nf5VgDdRcgqXcWmusRjowJpH2W/4MdKMc/2K2mFGS4yn0IEdz1q86JBci6Qdz38BEyQRhhtRqr/b4hNW+dKzvhgBgghRpitiJxPu+KsQmx3nMB2CCjE01YB0KbIG95N72W5UvTmwZ2Xa1dxSvlJukPZdOg7Y4luIddGwn5fcD9r0Alsk8yLXvFZ9Q+bmJdeb6Wlkg/ffT/jnBDU2PUQVC39/zbhFJnoDofMUr0OLJh4DFQh+v4mlAE5OJ1b+3ElpyFjg2Mp/6xTBKOpaYnkU1hllJYtnjkabFdOBlglDKJsI0irJdlKFoqreL+0PwA7RsQUmx02NFrdlTm/Srq1YDY4PvucczsrUZrF5aVogfkFaLi1dmz740vLRKdpX5IMGvuFsENUzSnSmMCR7XNaOlrxz1HEV03pQHLflEEQE28SVh7TVVgarwR+Iquk/pxdVCYI6eq5rKN5zT84WlxNpiA5fBDQQ/VT1HIRWvuLYn1/SOkj8ztjIoyrtlSLf5RhxS3OWEHxEWOt8U+U+2MMDZvdy4xvaGLktQdtrvP0FEsStOEnZPVLB5YgEiFYUJr/J7Kk1qM81nm/xFpVOnBBzH3PZLWFJVU=
#  file: target/release-test.jar
  file: "${DEPLOYED_FILE}"
  skip_cleanup: true
  on:
#    tags: true
    repo: SzFMV2018-Tavasz/release-test
